version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  maven: circleci/maven@1.4.1
jobs:
  build-and-test:
    working_directory: ~/ce-team-project-backend
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
          working_directory: ~/ce-team-project-backend
      - run:
          name: Test
          command: mvn test
          working_directory: ~/ce-team-project-backend
  build-image-and-push:
    working_directory: ~/ce-team-project-backend
    docker:
      - image: cimg/aws:2023.05
    steps:
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          repo: ce-tfotc-ecr-backend
          path: .
          build-path: .
          tag: ${CIRCLE_BUILD_NUM} 
workflows:
  demo-app-pipeline: 
    jobs:
      - build-and-test
      - build-image-and-push:
          context: TFOTC-Project
          requires:
            - build-and-test